// Pool for the Gadget game mode
export interface GadgetEntry {
  brawlerKey: string;
  gadgetName: string;
  gadgetDescription: string;
}

// One gadget per brawler — pick the most recognisable one
export const GADGET_POOL: GadgetEntry[] = [
  { brawlerKey: "shelly",    gadgetName: "Fast Forward",         gadgetDescription: "Shelly dashes forward, leaving a trail of pellets behind her." },
  { brawlerKey: "colt",      gadgetName: "Speedloader",          gadgetDescription: "Colt instantly reloads 2 ammo." },
  { brawlerKey: "bull",      gadgetName: "T-Bone Injector",      gadgetDescription: "Bull instantly recovers 2000 health." },
  { brawlerKey: "brock",     gadgetName: "Rocket Fuel",          gadgetDescription: "Brock's next attack becomes a mega rocket dealing 700 extra damage with a wider explosion." },
  { brawlerKey: "dynamike",  gadgetName: "Fidget Spinner",       gadgetDescription: "Dynamike spins and throws sticks of dynamite in all directions." },
  { brawlerKey: "bo",        gadgetName: "Super Totem",          gadgetDescription: "Bo places a totem that charges the Super of nearby friendly Brawlers." },
  { brawlerKey: "el_primo",  gadgetName: "Suplex Supplement",    gadgetDescription: "El Primo grabs the nearest enemy and throws them behind himself." },
  { brawlerKey: "barley",    gadgetName: "Herbal Tonic",         gadgetDescription: "Barley heals all nearby friendly Brawlers for 1200 health." },
  { brawlerKey: "poco",      gadgetName: "Protective Tunes",     gadgetDescription: "Poco gives nearby friendly Brawlers a shield that blocks 900 damage." },
  { brawlerKey: "rosa",      gadgetName: "Grow Light",           gadgetDescription: "Rosa's bush spawns immediately in her current location." },
  { brawlerKey: "jessie",    gadgetName: "Recoil Spring",        gadgetDescription: "Jessie's Scrappy turret fires in all directions for 2 seconds." },
  { brawlerKey: "nita",      gadgetName: "Bear Paws",            gadgetDescription: "Nita sends out a shockwave that stuns enemies for 1 second." },
  { brawlerKey: "mortis",    gadgetName: "Combo Spinner",        gadgetDescription: "Mortis swings his shovel quickly, dealing 900 damage to all nearby enemies." },
  { brawlerKey: "crow",      gadgetName: "Defense Booster",      gadgetDescription: "Crow grants a 400-HP shield to himself and nearby allies for 3 seconds." },
  { brawlerKey: "spike",     gadgetName: "Popping Pincushion",   gadgetDescription: "Spike launches spines outwards in all directions from his current location." },
  { brawlerKey: "leon",      gadgetName: "Lollipop Drop",        gadgetDescription: "Leon drops a lollipop that heals him for 2200 health over time." },
  { brawlerKey: "sandy",     gadgetName: "Humbug",               gadgetDescription: "Sandy creates a swirling sandstorm that damages enemies for 400 per second for 3 seconds." },
  { brawlerKey: "amber",     gadgetName: "Fuel'd Up",            gadgetDescription: "Amber sprays extra fuel onto her Super fire, permanently increasing it for a few seconds." },
  { brawlerKey: "meg",       gadgetName: "Jolting Volts",        gadgetDescription: "Meg's mech fires an electric pulse that stuns enemies in range for 1.5 seconds." },
  { brawlerKey: "surge",     gadgetName: "Power Surge",          gadgetDescription: "Surge immediately gets a free upgrade to the next level of his Super." },
  { brawlerKey: "colette",   gadgetName: "Push It",              gadgetDescription: "Colette launches herself backward, dealing damage to any enemies nearby." },
  { brawlerKey: "lou",       gadgetName: "Cryo Syrup",           gadgetDescription: "Lou drops an ice patch that slows enemies who walk over it." },
  { brawlerKey: "belle",     gadgetName: "Nest Egg",             gadgetDescription: "Belle places a stationary mine that explodes for 1200 damage when stepped on." },
  { brawlerKey: "squeak",    gadgetName: "Residue",              gadgetDescription: "Squeak's next attack leaves residue on hit enemies, marking them to explode." },
  { brawlerKey: "buzz",      gadgetName: "Residual Stun",        gadgetDescription: "Buzz sends out a stun wave around himself, stunning nearby enemies for 1 second." },
  { brawlerKey: "griff",     gadgetName: "Piggy Bank",           gadgetDescription: "Griff shatters his piggy bank, launching coins in all directions." },
  { brawlerKey: "gene",      gadgetName: "Lamp Blowout",         gadgetDescription: "Gene launches wisps that heal all nearby friendly Brawlers for 600 health." },
  { brawlerKey: "max",       gadgetName: "Sneaky Sneakers",      gadgetDescription: "Max teleports to a location within range and briefly gains invisibility." },
  { brawlerKey: "mr_p",      gadgetName: "Porter Reinforcement", gadgetDescription: "Mr. P calls in a respawning porter suitcase immediately." },
  { brawlerKey: "piper",     gadgetName: "Auto Aimer",           gadgetDescription: "Piper launches a burst of grenades around her." },
  { brawlerKey: "pam",       gadgetName: "Pulse Modulator",      gadgetDescription: "Pam's healing turret instantly heals all nearby allies for 1200 health." },
  { brawlerKey: "frank",     gadgetName: "Active Noise Canceling", gadgetDescription: "Frank creates an explosion around himself, knocking back enemies." },
  { brawlerKey: "bibi",      gadgetName: "Vitamin Booster",      gadgetDescription: "Bibi's Home Run shield is instantly recharged and temporarily boosted." },
  { brawlerKey: "bea",       gadgetName: "Rattled Hive",         gadgetDescription: "Bea summons a swarm of bees that chase the nearest enemy." },
  { brawlerKey: "nani",      gadgetName: "Warp Blast",           gadgetDescription: "Nani teleports to Peep's position, causing it to explode for 1400 damage." },
  { brawlerKey: "edgar",     gadgetName: "Hard Landing",         gadgetDescription: "Edgar crashes down at his location, knocking back and damaging nearby enemies." },
  { brawlerKey: "gale",      gadgetName: "Twister",              gadgetDescription: "Gale launches a tornado that pulls in nearby enemies." },
  { brawlerKey: "darryl",    gadgetName: "Recoiling Rotator",    gadgetDescription: "Darryl spins his barrel, deflecting all projectiles for 1 second." },
  { brawlerKey: "penny",     gadgetName: "Plunder",              gadgetDescription: "Penny's cannonball instantly splits into 8 mini-cannonballs in all directions." },
  { brawlerKey: "jacky",     gadgetName: "Pneumatic Booster",    gadgetDescription: "Jacky increases her movement speed and gains a shield for 3 seconds." },
  { brawlerKey: "carl",      gadgetName: "Protective Pirouette", gadgetDescription: "Carl deflects all incoming projectiles for 1 second while his pick is away." },
  { brawlerKey: "emz",       gadgetName: "Friendzoner",          gadgetDescription: "Emz pushes all enemies away from her current position." },
  { brawlerKey: "stu",       gadgetName: "Breakthrough",         gadgetDescription: "Stu's next attack passes through obstacles and enemies." },
  { brawlerKey: "fang",      gadgetName: "Roundhouse Kick",      gadgetDescription: "Fang delivers a powerful kick that pushes nearby enemies back." },
  { brawlerKey: "eve",       gadgetName: "Unearth",              gadgetDescription: "Eve summons 3 baby Parasites immediately from her current position." },
  { brawlerKey: "janet",     gadgetName: "Stage Dive",           gadgetDescription: "Janet dives to a location and stuns enemies around her landing point." },
  { brawlerKey: "bonnie",    gadgetName: "Hop Skip Jump",        gadgetDescription: "Bonnie leaps forward and gains a brief speed boost." },
  { brawlerKey: "otis",      gadgetName: "Dormant Star",         gadgetDescription: "Otis places a stationary star that silences enemies who walk near it." },
  { brawlerKey: "sam",       gadgetName: "Magnetic Field",       gadgetDescription: "Sam's knuckle busters orbit him and attract nearby enemies toward him." },
  { brawlerKey: "buster",    gadgetName: "Blockbuster",          gadgetDescription: "Buster charges forward, absorbing projectiles with his shield." },
  { brawlerKey: "gray",      gadgetName: "Portal Panic",         gadgetDescription: "Gray opens portals around all enemies, briefly confusing their controls." },
  { brawlerKey: "mandy",     gadgetName: "Hard Candy",           gadgetDescription: "Mandy releases a shockwave of candy that pushes enemies away." },
  { brawlerKey: "pearl",     gadgetName: "Overload",             gadgetDescription: "Pearl releases all stored heat in a ring of fire around herself." },
  { brawlerKey: "hank",      gadgetName: "储存 Energy",          gadgetDescription: "Hank extends his preparation time to charge up an even larger bubble." },
  { brawlerKey: "chester",   gadgetName: "Candy Beans",          gadgetDescription: "Chester eats some candy, randomly healing or gaining a shield effect." },
];
