// AUTO-GENERATED by scripts/generate-data.mjs — do not edit manually
// Re-run: node scripts/generate-data.mjs (after running scrape-wiki-stats.mjs for full stats)

export type BrawlerRarity = "Common" | "Rare" | "Super Rare" | "Epic" | "Mythic" | "Legendary" | "Ultra Legendary";
export type BrawlerClass = "Damage Dealer" | "Tank" | "Marksman" | "Assassin" | "Support" | "Controller" | "Healer" | "Hybrid";
export type BrawlerSpeed = "Slow" | "Normal" | "Fast" | "Very Fast";
export type BrawlerReload = "Slow" | "Normal" | "Fast" | "Very Fast";

export interface BrawlerStats {
  rarity: BrawlerRarity;
  class: BrawlerClass;
  speed: BrawlerSpeed;
  attackRange: "Short" | "Mid" | "Long";
  reload: BrawlerReload;
  releaseYear: number;
  hyperchargeName: string | null;
  hyperchargeDescription: string | null;
}

export const BRAWLER_STATS: Record<string, BrawlerStats> = {
  alli: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Short", reload: "Slow", releaseYear: 2025, hyperchargeName: "Swamp Snacking", hyperchargeDescription: "Alli's Super damages for 25% of enemies max health. Damaging enemies heals Alli for 20% of damage dealt." },
  amber: { rarity: "Legendary", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2020, hyperchargeName: "Oil Spill", hyperchargeDescription: "Super's oil spill area is increased. Oil keeps burning for 3 seconds after being lit on fire." },
  angelo: { rarity: "Epic", class: "Marksman", speed: "Very Fast", attackRange: "Long", reload: "Fast", releaseYear: 2024, hyperchargeName: "In My Element", hyperchargeDescription: "During Hypercharge, the Super will follow Angelo!" },
  ash: { rarity: "Epic", class: "Tank", speed: "Normal", attackRange: "Mid", reload: "Fast", releaseYear: 2021, hyperchargeName: "Rat King", hyperchargeDescription: "Little Helper spawns 5 more rats!" },
  barley: { rarity: "Rare", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2017, hyperchargeName: "Bottled-Up Rage", hyperchargeDescription: "Barley hurls 3 big brews that also destroy all bushes on impact." },
  bea: { rarity: "Epic", class: "Marksman", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2019, hyperchargeName: "Protect The Queen", hyperchargeDescription: "Bea's Super projectiles split into 2 when at max distance (and on hit), increasing her Super's distance and spread even more." },
  belle: { rarity: "Epic", class: "Marksman", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2021, hyperchargeName: "Magnetic", hyperchargeDescription: "Belle's spotting shot automatically follows the closest target." },
  berry: { rarity: "Epic", class: "Support", speed: "Normal", attackRange: "Mid", reload: "Slow", releaseYear: 2024, hyperchargeName: "Double Scoops", hyperchargeDescription: "Sweet Swirl drops double the scoops of ice cream!" },
  bibi: { rarity: "Epic", class: "Tank", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2019, hyperchargeName: "Out Of Bounds", hyperchargeDescription: "Bibi's bouncing ball splits when hitting an enemy" },
  bo: { rarity: "Epic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2017, hyperchargeName: "Catch A Bear", hyperchargeDescription: "Bo's Super deploys 5 mines instead of 3. These do not override any mines already placed by his Super, so it is possible to have more than 7 mines on the map!" },
  bonnie: { rarity: "Epic", class: "Marksman", speed: "Slow", attackRange: "Long", reload: "Fast", releaseYear: 2022, hyperchargeName: "Daredevil", hyperchargeDescription: "Bonnie stuns enemies for 1 secs when firing and landing from Clyde, plus she splits damage dealing teeth around her." },
  brock: { rarity: "Rare", class: "Marksman", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2017, hyperchargeName: "Rocket Barrage", hyperchargeDescription: "Brock fires a Rocket Barrage, raining down rockets in the targeted area simultaneously in 4 waves." },
  bull: { rarity: "Rare", class: "Tank", speed: "Fast", attackRange: "Mid", reload: "Normal", releaseYear: 2017, hyperchargeName: "Jaws Of Steel", hyperchargeDescription: "Bulldozer reduces damage taken by 80%." },
  buster: { rarity: "Mythic", class: "Tank", speed: "Fast", attackRange: "Mid", reload: "Normal", releaseYear: 2022, hyperchargeName: "Plot Armor", hyperchargeDescription: "Buster's Shield is now 360 degress around him and reflected projectiles deal more damage!" },
  buzz: { rarity: "Mythic", class: "Assassin", speed: "Fast", attackRange: "Short", reload: "Fast", releaseYear: 2021, hyperchargeName: "Buzzwatch", hyperchargeDescription: "Buzz's torpedo can now be used again if he hits a wall" },
  byron: { rarity: "Mythic", class: "Support", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2020, hyperchargeName: "Unstable Concoction", hyperchargeDescription: "Byron's Super also fires his main attack in all directions from the point of impact." },
  carl: { rarity: "Super Rare", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2019, hyperchargeName: "Flamespin", hyperchargeDescription: "Carl gains a flame trail while using his Super. The trail burns on contact, causing damage over time." },
  charlie: { rarity: "Mythic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2023, hyperchargeName: "Pestilence", hyperchargeDescription: "Cocoon spawns 3 spiders that seek and attack the nearest enemies." },
  chester: { rarity: "Legendary", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2022, hyperchargeName: "Crunchy, Chewy, Gooey", hyperchargeDescription: "Chester combines 3 of his Super abilities into one. He throws a sweet that explodes and deals damage, spreads a poison cloud, and leaves a lingering slowing area to finish." },
  chuck: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Mid", reload: "Slow", releaseYear: 2023, hyperchargeName: "Full Steam Ahead!", hyperchargeDescription: "Chuck has unlimited range on his next dash and leaves clouds of damaging steam behind him!" },
  clancy: { rarity: "Mythic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2024, hyperchargeName: "Recall Of Duty", hyperchargeDescription: "Clancy's Super paintballs pierce enemies then quickly return to him, dealing damage again." },
  colette: { rarity: "Epic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2020, hyperchargeName: "Teen Spirit", hyperchargeDescription: "Colette's spirit follows her during her dash, damaging enemies on the way." },
  colt: { rarity: "Rare", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2017, hyperchargeName: "Dual Wielding", hyperchargeDescription: "Bullet Storm is 120% wider." },
  cordelius: { rarity: "Legendary", class: "Assassin", speed: "Very Fast", attackRange: "Mid", reload: "Fast", releaseYear: 2023, hyperchargeName: "Complete Darkness", hyperchargeDescription: "Cordelius slows down his targets when sending them to the Shadow Realm." },
  crow: { rarity: "Legendary", class: "Assassin", speed: "Very Fast", attackRange: "Long", reload: "Fast", releaseYear: 2017, hyperchargeName: "Utility Knives", hyperchargeDescription: "Crow's knives are piercing and are returning like a boomerang." },
  darryl: { rarity: "Super Rare", class: "Tank", speed: "Fast", attackRange: "Mid", reload: "Normal", releaseYear: 2017, hyperchargeName: "Barrel O' Bullets", hyperchargeDescription: "Shoots his shotguns around himself during a Barrel Roll. Each shot does 600 damage each." },
  doug: { rarity: "Mythic", class: "Support", speed: "Fast", attackRange: "Short", reload: "Normal", releaseYear: 2023, hyperchargeName: "Free Toppings", hyperchargeDescription: "Doug's Snack Attack is also mirrored for the ally buffed with the Second Serving." },
  draco: { rarity: "Legendary", class: "Tank", speed: "Normal", attackRange: "Mid", reload: "Fast", releaseYear: 2024, hyperchargeName: "Fire And Flames", hyperchargeDescription: "Draco's dragon breathes more flames in a wider area and with longer range." },
  dynamike: { rarity: "Super Rare", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2017, hyperchargeName: "Boomer", hyperchargeDescription: "Super bomb spawns smaller bombs." },
  edgar: { rarity: "Epic", class: "Assassin", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2020, hyperchargeName: "Outburst", hyperchargeDescription: "After using Super gain charging speed and reload speed for few seconds." },
  eight_bit: { rarity: "Super Rare", class: "Damage Dealer", speed: "Slow", attackRange: "Long", reload: "Normal", releaseYear: 2019, hyperchargeName: "Aimbot", hyperchargeDescription: "8-Bit's turret now has a laser that shoot nearby enemies. Shots do 230 damage." },
  el_primo: { rarity: "Rare", class: "Tank", speed: "Fast", attackRange: "Short", reload: "Fast", releaseYear: 2017, hyperchargeName: "Gravity Leap", hyperchargeDescription: "El Primo drops an Intergalactic Elbow that brings enemies to the Epicenter." },
  emz: { rarity: "Epic", class: "Controller", speed: "Normal", attackRange: "Mid", reload: "Slow", releaseYear: 2019, hyperchargeName: "Overhyped Haze", hyperchargeDescription: "Emz pushes enemies to the outer edge of her Super on activation and follows up with a dose of her spray." },
  eve: { rarity: "Mythic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2022, hyperchargeName: "Generations", hyperchargeDescription: "Baby Boom now spawns hatchlings over time!" },
  fang: { rarity: "Mythic", class: "Assassin", speed: "Fast", attackRange: "Short", reload: "Fast", releaseYear: 2022, hyperchargeName: "Dragon Kick", hyperchargeDescription: "Charge through walls while dropping popcorn on the way." },
  finx: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Fast", releaseYear: 2025, hyperchargeName: "Temporal Traveling", hyperchargeDescription: "Finx activates an additional Time Warp around himself that follows his movement." },
  frank: { rarity: "Epic", class: "Tank", speed: "Fast", attackRange: "Mid", reload: "Fast", releaseYear: 2018, hyperchargeName: "Seismic Smash", hyperchargeDescription: "Frank's Super now hits an entire circle around him!" },
  gale: { rarity: "Epic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2020, hyperchargeName: "Blizzard", hyperchargeDescription: "Gale's Super is slightly wider and fires twice, pushing enemies even further away!" },
  gene: { rarity: "Mythic", class: "Controller", speed: "Normal", attackRange: "Short", reload: "Slow", releaseYear: 2019, hyperchargeName: "Hyper Hands", hyperchargeDescription: "Gene's Super splits into 3 different hands, each being able to grab one enemy. First goes straight, and the other 2 go diagonally." },
  gigi: { rarity: "Mythic", class: "Damage Dealer", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2025, hyperchargeName: "Pas De Deux", hyperchargeDescription: "Gigi's Super deals damage when appearing at a target location, as well as returning to the original location." },
  glowy: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2026, hyperchargeName: "You Need a Friend", hyperchargeDescription: "Super now surrounds Glowy, and any enemies hit will be feared! Feared targets now take 25% extra damage from all sources." },
  gray: { rarity: "Mythic", class: "Support", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2022, hyperchargeName: "Another Dimension", hyperchargeDescription: "Gray opens a new pair of portals that shields him and allies for 1000 when they pass through." },
  griff: { rarity: "Epic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2021, hyperchargeName: "Tax Rebate", hyperchargeDescription: "Griff's banknotes multiply at max range before returning, with the newly created banknotes after a delay. They also pierce the environment." },
  grom: { rarity: "Epic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2021, hyperchargeName: "Grom Bomb Goes Boom!", hyperchargeDescription: "Grom's Super gains a secondary explosion after the first, in an X-pattern. This explosion also deals damage, breaks walls and knocks enemies back." },
  gus: { rarity: "Super Rare", class: "Support", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2022, hyperchargeName: "Spooky Pop", hyperchargeDescription: "On impact, Gus' Super will drop spirits in all directions that deal damage to enemies and heal teammates!" },
  hank: { rarity: "Epic", class: "Tank", speed: "Normal", attackRange: "Short", reload: "Fast", releaseYear: 2023, hyperchargeName: "Homing Fish-Iles", hyperchargeDescription: "The Fish Torpedoes that Hank fires with his Super have been upgraded to home in on targets!" },
  jacky: { rarity: "Super Rare", class: "Tank", speed: "Fast", attackRange: "Short", reload: "Normal", releaseYear: 2020, hyperchargeName: "Seismic Event", hyperchargeDescription: "Holey Moley slows down nearby enemies for 1.5 seconds." },
  jae_yong: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2025, hyperchargeName: "Crowd-Pleaser", hyperchargeDescription: "Jae's Super has a reduced cooldown during Hypercharge, and each Super activation is boosted." },
  janet: { rarity: "Mythic", class: "Marksman", speed: "Normal", attackRange: "Mid", reload: "Normal", releaseYear: 2022, hyperchargeName: "Magnum Opus", hyperchargeDescription: "Janet retains full movement control during her Super." },
  jessie: { rarity: "Super Rare", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2017, hyperchargeName: "Scrappy 2.0", hyperchargeDescription: "Jessie's turret has 50% more health and deals 20% more damage." },
  juju: { rarity: "Mythic", class: "Damage Dealer", speed: "Normal", attackRange: "Mid", reload: "Normal", releaseYear: 2024, hyperchargeName: "Bokor", hyperchargeDescription: "Juju summons a Hypercharged Gris-Gris giving him bigger needles, 25% more speed, 20% more health, and 20% more damage." },
  kaze: { rarity: "Ultra Legendary", class: "Damage Dealer", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2025, hyperchargeName: "Ancient Energy", hyperchargeDescription: "The center of the Fan Storm damages enemies over time." },
  kenji: { rarity: "Legendary", class: "Assassin", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2024, hyperchargeName: "All You Can Eat", hyperchargeDescription: "Kenji pulls nearby enemies to the middle of his Super" },
  kit: { rarity: "Legendary", class: "Support", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2023, hyperchargeName: "Making Biscuits", hyperchargeDescription: "Kit's Super stuns the enemy but he can move and attack normally. Attaching to teammates will heal them more and his Yarn Balls have a longer range." },
  larry_and_lawrie: { rarity: "Epic", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Slow", releaseYear: 2024, hyperchargeName: "The Three-Bot Problem", hyperchargeDescription: "Larry calls an extra prototype Lawrie bot for backup, which deals more damage and has higher health than plain ol' Lawrie. Gadgets that affect Lawrie only apply to the \"original\" model." },
  leon: { rarity: "Legendary", class: "Assassin", speed: "Very Fast", attackRange: "Long", reload: "Normal", releaseYear: 2018, hyperchargeName: "Limbo", hyperchargeDescription: "Leon stays invisible while attacking his enemies." },
  lily: { rarity: "Mythic", class: "Assassin", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2024, hyperchargeName: "Germinate", hyperchargeDescription: "Lily's Flourish now bounces off walls, and transports the enemy and Lily to the Shadow Realm for 5 seconds." },
  lola: { rarity: "Epic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2021, hyperchargeName: "Inflated Ego", hyperchargeDescription: "Spawns a mega inflated Ego with increased damage and health." },
  lou: { rarity: "Mythic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2020, hyperchargeName: "Slushie Storm", hyperchargeDescription: "Lou's Super instantly freezes enemies in the area." },
  lumi: { rarity: "Mythic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Very Fast", releaseYear: 2025, hyperchargeName: "Drum Solo", hyperchargeDescription: "The final explosion from Lumi's Super has an extra blast on both sides." },
  maisie: { rarity: "Epic", class: "Marksman", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2023, hyperchargeName: "Aftermath", hyperchargeDescription: "Maisie's Super also shoots her basic attack projectiles around her to all directions." },
  mandy: { rarity: "Epic", class: "Marksman", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2022, hyperchargeName: "Sugar For All!", hyperchargeDescription: "Mandy fires her Super in three different directions." },
  max: { rarity: "Mythic", class: "Support", speed: "Very Fast", attackRange: "Long", reload: "Fast", releaseYear: 2019, hyperchargeName: "Unlimited Energy", hyperchargeDescription: "Max throws an energy drink to each team member, increasing their movement speed and granting them 25% Super charge." },
  meeple: { rarity: "Epic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2025, hyperchargeName: "The Last Rulebender", hyperchargeDescription: "Super covers a larger area. It now allows Meeple and their teammates to walk through walls and over water." },
  meg: { rarity: "Legendary", class: "Tank", speed: "Very Fast", attackRange: "Long", reload: "Fast", releaseYear: 2021, hyperchargeName: "Tungsten Toughness", hyperchargeDescription: "Meg's Mecha has an increased swipe range when activating its Super. While out of the Mecha, Meg pops a defensive shield for protection." },
  melodie: { rarity: "Mythic", class: "Assassin", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2024, hyperchargeName: "Flash Mob", hyperchargeDescription: "Melodie adds up to 3 Hypercharge notes using Catchy Chorus. Hypercharge notes do 600 damage." },
  mico: { rarity: "Mythic", class: "Assassin", speed: "Very Fast", attackRange: "Mid", reload: "Slow", releaseYear: 2023, hyperchargeName: "Sound Check", hyperchargeDescription: "Mico's Super also stuns nearby enemies after landing for 1.5 seconds." },
  mina: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Fast", releaseYear: 2025, hyperchargeName: "Triplecane", hyperchargeDescription: "Super now fires 3 hurricanes in a cone shape, which can bounce." },
  moe: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2024, hyperchargeName: "The Big Cheese", hyperchargeDescription: "Moe's Driller has longer range and lasts for longer." },
  mortis: { rarity: "Mythic", class: "Assassin", speed: "Very Fast", attackRange: "Short", reload: "Slow", releaseYear: 2017, hyperchargeName: "Blood Boomerang", hyperchargeDescription: "Life Blood now also returns to Mortis, allowing for double damage and healing." },
  mr_p: { rarity: "Mythic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2020, hyperchargeName: "Super Porters! Assemble!", hyperchargeDescription: "Mr. P's home base now spawns much stronger porters and he can have two active 'Super Porters' at the same time." },
  najia: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Mid", reload: "Fast", releaseYear: 2026, hyperchargeName: null, hyperchargeDescription: null },
  nani: { rarity: "Epic", class: "Marksman", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2020, hyperchargeName: "Big Peep", hyperchargeDescription: "Peep grows in size during travel." },
  nita: { rarity: "Rare", class: "Damage Dealer", speed: "Normal", attackRange: "Mid", reload: "Fast", releaseYear: 2017, hyperchargeName: "Hyperbearing", hyperchargeDescription: "Nita hypercharges Bruce, making him increase in size, giving him 15% increased movement speed and 20% increased health." },
  ollie: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Mid", reload: "Normal", releaseYear: 2025, hyperchargeName: "Ain'T No Half-Supering", hyperchargeDescription: "Ollie now dashes farther and faster! His music blast area is larger and it won't consume ammo when it starts charging." },
  otis: { rarity: "Mythic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2022, hyperchargeName: "Silent Stunner", hyperchargeDescription: "Otis' Super now also stuns for 1.5 seconds on impact." },
  pam: { rarity: "Epic", class: "Support", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2017, hyperchargeName: "Mama'S Love", hyperchargeDescription: "Pam's turret heals on deploy. It continues to heal Brawlers over their max health by providing them with a decaying shield." },
  pearl: { rarity: "Epic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2023, hyperchargeName: "Pyrolytic", hyperchargeDescription: "Let Out Some Steam leaves a burning area behind for 4.5 seconds." },
  penny: { rarity: "Super Rare", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2018, hyperchargeName: "New Lobber", hyperchargeDescription: "Penny deploys a bigger cannon that shoots 2 cannonballs at a time instead of 1" },
  pierce: { rarity: "Legendary", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2025, hyperchargeName: "Second Wave", hyperchargeDescription: "Super fires 2 waves of projectiles, 2nd wave deals 50% less damage. Projectiles pierce Brawlers." },
  piper: { rarity: "Epic", class: "Marksman", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2017, hyperchargeName: "Boppin'", hyperchargeDescription: "Piper drops even more bombs as she departs at an increased speed! She also destroys terrain when she lands." },
  poco: { rarity: "Rare", class: "Support", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2017, hyperchargeName: "Medic'S Melody", hyperchargeDescription: "Encore now overheals, adding a decaying shield for the amount overhealed. Shield lasts for 5 seconds." },
  r_t: { rarity: "Mythic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2023, hyperchargeName: "360-Degree Surveillance", hyperchargeDescription: "Damaging security lasers surround R-T and his legs after using a Hypercharged Super." },
  rico: { rarity: "Super Rare", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2017, hyperchargeName: "Trick Shot King", hyperchargeDescription: "Rico's Super's projectiles bounce even further!" },
  rosa: { rarity: "Rare", class: "Tank", speed: "Fast", attackRange: "Short", reload: "Fast", releaseYear: 2019, hyperchargeName: "Grasping Roots", hyperchargeDescription: "Rosa slows down all nearby enemies while her Super is active." },
  ruffs: { rarity: "Mythic", class: "Support", speed: "Normal", attackRange: "Long", reload: "Fast", releaseYear: 2021, hyperchargeName: "The Goodest Boy", hyperchargeDescription: "Ruffs' Super deals 25% more damage and his power-up fully charges a Hypercharge." },
  sam: { rarity: "Epic", class: "Assassin", speed: "Fast", attackRange: "Short", reload: "Normal", releaseYear: 2022, hyperchargeName: "Hyper Fist", hyperchargeDescription: "Sam's Knuckle Busters travel faster and will fully charge his Super if they hit an enemy Brawler during the Hypercharge." },
  sandy: { rarity: "Legendary", class: "Controller", speed: "Fast", attackRange: "Mid", reload: "Normal", releaseYear: 2019, hyperchargeName: "Swift Winds", hyperchargeDescription: "Sandy grants himself and his allies 20% increased movement speed while inside of Sandstorm. His Super will also silence enemies for 0.5 seconds when it lands." },
  shade: { rarity: "Epic", class: "Assassin", speed: "Very Fast", attackRange: "Short", reload: "Fast", releaseYear: 2024, hyperchargeName: "The Frightener", hyperchargeDescription: "Shade's attacks during its Hypercharged Super all deal deal maximum damage, even if the enemy is not hugged in the center." },
  shelly: { rarity: "Common", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2017, hyperchargeName: "Double Barrel", hyperchargeDescription: "Super Shell is 33% larger." },
  sirius: { rarity: "Ultra Legendary", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2026, hyperchargeName: "Unlimited Power!", hyperchargeDescription: "Shadows summoned during Hypercharge have increased damage and health." },
  spike: { rarity: "Legendary", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2017, hyperchargeName: "Blooming Season", hyperchargeDescription: "Stick Around has 20% larger area." },
  sprout: { rarity: "Mythic", class: "Damage Dealer", speed: "Normal", attackRange: "Mid", reload: "Normal", releaseYear: 2020, hyperchargeName: "Thorns", hyperchargeDescription: "Sprout's vine hedge now damages nearby enemies." },
  squeak: { rarity: "Mythic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2021, hyperchargeName: "Bouncy Blob", hyperchargeDescription: "The Sticky Blombs from Squeak's Super now bounce and split one more time." },
  stu: { rarity: "Epic", class: "Assassin", speed: "Normal", attackRange: "Long", reload: "Normal", releaseYear: 2021, hyperchargeName: "Infinitro", hyperchargeDescription: "Stu's Super can be used continuously while Hypercharged." },
  surge: { rarity: "Legendary", class: "Damage Dealer", speed: "Slow", attackRange: "Mid", reload: "Slow", releaseYear: 2020, hyperchargeName: "Stage 5", hyperchargeDescription: "Surge's shots now ALWAYS split and have increased range!" },
  tara: { rarity: "Mythic", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2017, hyperchargeName: "Supermassive", hyperchargeDescription: "Gravity has 20% larger area." },
  tick: { rarity: "Super Rare", class: "Damage Dealer", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2019, hyperchargeName: "Headstrong", hyperchargeDescription: "Tick quickly deploys his head, charging enemies faster and leaving behind 6 of his minimines on explosion." },
  trunk: { rarity: "Epic", class: "Damage Dealer", speed: "Fast", attackRange: "Short", reload: "Normal", releaseYear: 2025, hyperchargeName: "Retread", hyperchargeDescription: "Trunk's Super causes them to leave ants on enemies which deal damage over time." },
  willow: { rarity: "Mythic", class: "Controller", speed: "Normal", attackRange: "Long", reload: "Slow", releaseYear: 2023, hyperchargeName: "Psychic Safety", hyperchargeDescription: "Willow gains an invulnerability shield on landing her Hex. She remains shielded until Hex is broken." },
  ziggy: { rarity: "Mythic", class: "Damage Dealer", speed: "Fast", attackRange: "Long", reload: "Normal", releaseYear: 2025, hyperchargeName: "The Grand Vortex", hyperchargeDescription: "A Hypercharged Super returns to Ziggy upon reaching its max range/lifetime." },
};

export function getBrawlerKeys(): string[] { return Object.keys(BRAWLER_STATS); }

export function getBrawlerDisplayName(key: string): string {
  return key
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ")
    .replace("Mr P", "Mr. P")
    .replace("Eight Bit", "8-Bit")
    .replace("Larry And Lawrie", "Larry & Lawrie")
    .replace("R T", "R-T")
    .replace("Jae Yong", "Jae-Yong");
}

export function brawlerMatchesSearch(key: string, query: string): boolean {
  return getBrawlerDisplayName(key).toLowerCase().includes(query.toLowerCase());
}

export function findExactMatchKey(query: string): string | null {
  const q = query.toLowerCase().trim();
  return getBrawlerKeys().find((k) => getBrawlerDisplayName(k).toLowerCase() === q) ?? null;
}

export const RARITY_ORDER: BrawlerRarity[] = [
  "Common", "Rare", "Super Rare", "Epic", "Mythic", "Legendary", "Ultra Legendary",
];
export const SPEED_ORDER: BrawlerSpeed[] = ["Slow", "Normal", "Fast", "Very Fast"];
export const RELOAD_ORDER: BrawlerReload[] = ["Slow", "Normal", "Fast", "Very Fast"];

export function compareOrdered<T>(a: T, b: T, order: T[]): "correct" | "higher" | "lower" {
  const ai = order.indexOf(a), bi = order.indexOf(b);
  if (ai === bi) return "correct";
  return ai > bi ? "higher" : "lower";
}
