/**
 * generate-data.mjs
 *
 * Generates lib/brawler-stats.ts, lib/brawler-gadgets.ts, lib/brawler-hypercharges.ts
 * and downloads brawler portrait images to public/Brawlers/.
 *
 * Data sources:
 *   - Brawlify API (https://api.brawlify.com/v1/brawlers): names, rarity, class,
 *     descriptions, gadget names+descriptions, imageUrl2 for portraits
 *   - Official Brawl Stars API JSON (local file): hypercharge names
 *   - scripts/wiki-stats.json (optional, generated by scrape-wiki-stats.mjs):
 *     speed, attackRange, reload, releaseYear — if absent, placeholder values are used
 *
 * Usage:
 *   1. Copy response_1773713042176.json to brawl-puzzle/scripts/
 *   2. node scripts/generate-data.mjs
 *   3. (Optional) node scripts/scrape-wiki-stats.mjs  →  node scripts/generate-data.mjs
 */

import fs from "fs";
import path from "path";
import https from "https";
import http from "http";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

// ── Helpers ───────────────────────────────────────────────────────────────────

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith("https") ? https : http;
    mod.get(url, { headers: { "User-Agent": "brawldly-data-gen/1.0" } }, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(new Error(`JSON parse error for ${url}: ${e.message}`)); }
      });
    }).on("error", reject);
  });
}

function downloadFile(url, destPath) {
  return new Promise((resolve) => {
    const mod = url.startsWith("https") ? https : http;
    const file = fs.createWriteStream(destPath);
    mod.get(url, { headers: { "User-Agent": "brawldly-data-gen/1.0" } }, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        file.close();
        fs.unlink(destPath, () => {});
        downloadFile(res.headers.location, destPath).then(resolve);
        return;
      }
      res.pipe(file);
      file.on("finish", () => { file.close(); resolve(); });
    }).on("error", () => { file.close(); fs.unlink(destPath, () => {}); resolve(); });
  });
}

// ── Name → internal key ───────────────────────────────────────────────────────
function nameToKey(name) {
  return name
    .toLowerCase()
    .replace(/mr\.?\s*p\b/g, "mr_p")
    .replace(/\b8.?bit\b/gi, "eight_bit")
    .replace(/larry\s*&\s*lawrie/g, "larry_and_lawrie")
    .replace(/\br-t\b/g, "r_t")
    .replace(/jae-yong/g, "jae_yong")
    .replace(/[^a-z0-9\s_]/g, "")
    .trim()
    .replace(/\s+/g, "_");
}

// ── Key → image filename (Title-Cased, dash-separated) ───────────────────────
function keyToFilename(key) {
  return key.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("-");
}

// ── Rarity mapping (add Ultra Legendary as a new tier) ───────────────────────
const RARITY_MAP = {
  "common": "Common",
  "rare": "Rare",
  "super rare": "Super Rare",
  "epic": "Epic",
  "mythic": "Mythic",
  "legendary": "Legendary",
  "ultra legendary": "Ultra Legendary",
};
function mapRarity(raw) {
  return RARITY_MAP[raw?.toLowerCase()] ?? "Common";
}

// No "Starting Brawler" rarity — Shelly is just "Common"

// ── Class mapping ─────────────────────────────────────────────────────────────
const VALID_CLASSES = new Set(["Damage Dealer","Tank","Marksman","Assassin","Support","Controller","Healer","Hybrid"]);
function mapClass(raw) {
  const title = raw?.split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  return VALID_CLASSES.has(title) ? title : "Damage Dealer";
}

// ── Title-case a string ───────────────────────────────────────────────────────
function toTitleCase(str) {
  return str.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  // 1. Load official Brawl Stars API JSON (for hypercharge names + brawler IDs)
  const jsonCandidates = [
    path.join(__dirname, "response_1773713042176.json"),
    path.join(ROOT, "..", "response_1773713042176.json"),
    "C:/Users/ivan_/Downloads/response_1773713042176.json",
  ];
  let officialItems = null;
  for (const p of jsonCandidates) {
    if (fs.existsSync(p)) {
      const raw = JSON.parse(fs.readFileSync(p, "utf8"));
      officialItems = raw.items ?? raw;
      console.log(`✓ Loaded ${officialItems.length} brawlers from ${p}`);
      break;
    }
  }
  if (!officialItems) {
    console.error("ERROR: Cannot find response_1773713042176.json.");
    console.error("Copy it to brawl-puzzle/scripts/ and re-run.");
    process.exit(1);
  }

  // Build official-API index: name.toLowerCase() → { hyperCharges, id }
  const officialByKey = {};
  for (const b of officialItems) {
    officialByKey[nameToKey(b.name)] = b;
  }

  // 2. Fetch Brawlify API
  console.log("Fetching Brawlify API…");
  let brawlifyList = [];
  try {
    const data = await fetchJson("https://api.brawlify.com/v1/brawlers");
    brawlifyList = data.list ?? [];
    console.log(`✓ Got ${brawlifyList.length} brawlers from Brawlify`);
  } catch (e) {
    console.error("Brawlify fetch failed:", e.message);
    process.exit(1);
  }

  // Index Brawlify by key
  const brawlifyByKey = {};
  for (const b of brawlifyList) {
    if (b.released) brawlifyByKey[nameToKey(b.name)] = b;
  }

  // 3. Load optional wiki-stats.json (from scrape-wiki-stats.mjs)
  const wikiStatsPath = path.join(__dirname, "wiki-stats.json");
  let wikiStats = {};
  if (fs.existsSync(wikiStatsPath)) {
    wikiStats = JSON.parse(fs.readFileSync(wikiStatsPath, "utf8"));
    console.log(`✓ Loaded wiki stats for ${Object.keys(wikiStats).length} brawlers`);
  } else {
    console.log("⚠ wiki-stats.json not found — speed/range/reload/year will be placeholders");
    console.log("  Run: node scripts/scrape-wiki-stats.mjs  to fill them in");
  }

  // 4. Ensure public/Brawlers/ exists
  const brawlersDir = path.join(ROOT, "public", "Brawlers");
  fs.mkdirSync(brawlersDir, { recursive: true });

  // 5. Build data arrays
  const brawlerStatsEntries = [];
  const gadgetEntries = [];

  // Use Brawlify as the source of truth for which brawlers exist (released only)
  // Then enrich with official JSON data
  const allKeys = [...new Set([
    ...Object.keys(brawlifyByKey),
    ...Object.keys(officialByKey),
  ])].sort();

  let imageCount = 0;
  let skippedImages = 0;

  for (const key of allKeys) {
    const bf = brawlifyByKey[key];
    const official = officialByKey[key];

    // Skip if Brawlify doesn't know this brawler (might be unreleased in official JSON)
    if (!bf) {
      console.log(`  skip ${key} (not in Brawlify released list)`);
      continue;
    }

    // Stats
    const rarity = mapRarity(bf.rarity?.name);
    const cls = mapClass(bf.class?.name);
    const hcName = official?.hyperCharges?.[0]?.name
      ? toTitleCase(official.hyperCharges[0].name)
      : null;
    const wiki = wikiStats[key] ?? {};
    const speed = wiki.speed ?? "Normal";
    const attackRange = wiki.attackRange ?? "Mid";
    const reload = wiki.reload ?? "Normal";
    const releaseYear = wiki.releaseYear ?? 2020;

    brawlerStatsEntries.push(
      `  ${key}: { rarity: "${rarity}", class: "${cls}", speed: "${speed}", attackRange: "${attackRange}", reload: "${reload}", releaseYear: ${releaseYear}, hyperchargeName: ${hcName ? JSON.stringify(hcName) : "null"}, hyperchargeDescription: null },`
    );

    // Gadgets — from Brawlify (has descriptions)
    for (const gadget of (bf.gadgets ?? [])) {
      gadgetEntries.push(
        `  { brawlerKey: "${key}", gadgetName: ${JSON.stringify(gadget.name)}, gadgetDescription: ${JSON.stringify(gadget.description ?? "")} },`
      );
    }

    // Hypercharge name embedded in brawler-stats entry (see hcName above).
    // Descriptions filled separately by: node scripts/scrape-hypercharge-descriptions.mjs

    // Download image (imageUrl2 = borderless portrait)
    if (bf.imageUrl2) {
      const filename = `${keyToFilename(key)}.png`;
      const imgPath = path.join(brawlersDir, filename);
      if (!fs.existsSync(imgPath)) {
        process.stdout.write(`  Downloading ${filename}… `);
        await downloadFile(bf.imageUrl2, imgPath);
        if (fs.existsSync(imgPath) && fs.statSync(imgPath).size > 0) {
          console.log("✓");
          imageCount++;
        } else {
          console.log("✗ (failed)");
          skippedImages++;
        }
      }
    }
  }

  // 6. Write lib/brawler-stats.ts
  const statsTs = `// AUTO-GENERATED by scripts/generate-data.mjs — do not edit manually
// Re-run: node scripts/generate-data.mjs (after running scrape-wiki-stats.mjs for full stats)

export type BrawlerRarity = "Common" | "Rare" | "Super Rare" | "Epic" | "Mythic" | "Legendary" | "Ultra Legendary";
export type BrawlerClass = "Damage Dealer" | "Tank" | "Marksman" | "Assassin" | "Support" | "Controller" | "Healer" | "Hybrid";
export type BrawlerSpeed = "Slow" | "Normal" | "Fast" | "Very Fast";
export type BrawlerReload = "Slow" | "Normal" | "Fast" | "Very Fast";

export interface BrawlerStats {
  rarity: BrawlerRarity;
  class: BrawlerClass;
  speed: BrawlerSpeed;
  attackRange: "Short" | "Mid" | "Long";
  reload: BrawlerReload;
  releaseYear: number;
  hyperchargeName: string | null;
  hyperchargeDescription: string | null;
}

export const BRAWLER_STATS: Record<string, BrawlerStats> = {
${brawlerStatsEntries.join("\n")}
};

export function getBrawlerKeys(): string[] { return Object.keys(BRAWLER_STATS); }

export function getBrawlerDisplayName(key: string): string {
  return key
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ")
    .replace("Mr P", "Mr. P")
    .replace("Eight Bit", "8-Bit")
    .replace("Larry And Lawrie", "Larry & Lawrie")
    .replace("R T", "R-T")
    .replace("Jae Yong", "Jae-Yong");
}

export function brawlerMatchesSearch(key: string, query: string): boolean {
  return getBrawlerDisplayName(key).toLowerCase().includes(query.toLowerCase());
}

export function findExactMatchKey(query: string): string | null {
  const q = query.toLowerCase().trim();
  return getBrawlerKeys().find((k) => getBrawlerDisplayName(k).toLowerCase() === q) ?? null;
}

export const RARITY_ORDER: BrawlerRarity[] = [
  "Common", "Rare", "Super Rare", "Epic", "Mythic", "Legendary", "Ultra Legendary",
];
export const SPEED_ORDER: BrawlerSpeed[] = ["Slow", "Normal", "Fast", "Very Fast"];
export const RELOAD_ORDER: BrawlerReload[] = ["Slow", "Normal", "Fast", "Very Fast"];

export function compareOrdered<T>(a: T, b: T, order: T[]): "correct" | "higher" | "lower" {
  const ai = order.indexOf(a), bi = order.indexOf(b);
  if (ai === bi) return "correct";
  return ai > bi ? "higher" : "lower";
}
`;

  fs.writeFileSync(path.join(ROOT, "lib", "brawler-stats.ts"), statsTs);
  console.log(`\n✓ lib/brawler-stats.ts written (${brawlerStatsEntries.length} brawlers)`);

  // 7. Write lib/brawler-gadgets.ts
  const gadgetsTs = `// AUTO-GENERATED by scripts/generate-data.mjs — do not edit manually

export interface GadgetEntry {
  brawlerKey: string;
  gadgetName: string;
  gadgetDescription: string;
}

export const GADGET_POOL: GadgetEntry[] = [
${gadgetEntries.join("\n")}
];
`;
  fs.writeFileSync(path.join(ROOT, "lib", "brawler-gadgets.ts"), gadgetsTs);
  console.log(`✓ lib/brawler-gadgets.ts written (${gadgetEntries.length} gadgets)`);

  // Note: hypercharge names are now embedded in brawler-stats.ts (hyperchargeName field).
  // Descriptions are filled by: node scripts/scrape-hypercharge-descriptions.mjs

  console.log(`\n✓ Images: ${imageCount} downloaded, ${skippedImages} failed`);
  console.log("\nDone! Next step:");
  console.log("  node scripts/scrape-wiki-stats.mjs   ← fills in speed/range/reload/year");
  console.log("  node scripts/generate-data.mjs        ← re-run after wiki scrape to apply values");
}

main().catch((e) => { console.error(e); process.exit(1); });
